name: Issue
description: For errata: spelling, wording, formatting, conflicting/inconsistent information, etc.
body:
  - type: markdown
    attributes:
      value: |
        * Please use issues for things like typos, wording, formatting, conflicting information, etc.
        * For discussions, suggestions and ideas, please use the [Discussions](https://github.com/container-interop/service-provider/discussions) tab.
  - type: checkboxes
    id: confirm
    attributes:
      label: Checklist
      description: "To save time, please confirm:"
      options:
        - label: I've read the entire PSR and meta documents.
          required: true
        - label: This is an issue with the content of the documents.
          required: true
  - type: textarea
    id: bug-description
    attributes:
      label: Issue
    validations:
      required: true
