name: Issue
description: File an issue
body:
  - type: markdown
    attributes:
      value: |
        Please use issues for things like typos, wording, formatting, conflicting information, etc.
        
        For discussions, suggestions and ideas, please use the [Discussions](https://github.com/container-interop/service-provider/discussions) tab.
  - type: textarea
    id: bug-description
    validations:
      required: true
